version: '3'

services:
  server:
    image: docker.rortic.us/bearacade
    environment:
      HOST:  http://1aa94714.ngrok.io
    build:
      context: ./
    command: "/usr/local/bin/npm run dev"
    ports:
      - 8000:8000
    volumes:
      - ./:/app
