version: '3'

services:
  server:
    image: docker.rortic.us/bearacade
    build:
      context: ./
    command: "/app/node_modules/.bin/nodemon /app/main.js"
    ports:
      - 8000:8000
    volumes:
      - ./server/build/:/app
      - ./server/node_modules:/app/node_modules
      - ./client/build/:/client